{% set name = "jaqs" %}
{% set version = "0.6.9.4" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "80d199e35bf7954c085f4dffa81d9b627e449341d2589287b3545c867f6039c7" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - future

    - jinja2
    - msgpack-python
    - pandas >=0.20.0
    - pyzmq
    - python-snappy
    - seaborn
    - six
  run:
    - python
    - future

    - jinja2
    - msgpack-python
    - pandas >=0.20.0
    - pyzmq
    - python-snappy
    - seaborn
    - six

test:
  imports:
    - jaqs
    - jaqs.data
    - jaqs.data.basic
    - jaqs.data.dataapi
    - jaqs.research
    - jaqs.research.signaldigger
    - jaqs.trade
    - jaqs.trade.analyze
    - jaqs.trade.event
    - jaqs.trade.tradeapi
    - jaqs.util

about:
  home: https://github.com/quantOS-org/JAQS
  license: Apache Software License
  license_family: APACHE
  license_file: ''
  summary: Open source quantitative research&trading framework.
  description: "Introduction\n============\n|pypi peoject version|\n|pypi pyversion|\n|pypi license|\n|travis ci|\n|covergae|\n\nJAQS\u662F\u4E00\u4E2A\u5F00\u6E90\u91CF\u5316\u7B56\u7565\u7814\u7A76\u5E73\
    \u53F0\uFF0C\u7531\u4EA4\u6613\u4E13\u5BB6\u548C\u91D1\u878D\u6280\u672F\u4E13\u5BB6\u5171\u540C\u8BBE\u8BA1\uFF0C\u5B9E\u73B0\u4E86\u81EA\u52A8\u5316\u4FE1\u53F7\u7814\u7A76\u3001\u9AD8\u6548\u7B56\
    \u7565\u5F00\u53D1\u548C\u591A\u7EF4\u5EA6\u56DE\u6D4B\u5206\u6790\uFF0C\u652F\u6301Alpha\u3001CTA\u3001\u5957\u5229\u7B49\u7B56\u7565\u7684\u5B9E\u73B0\u3002JAQS\u4ECE\u5B9E\u6218\u800C\u6765\uFF0C\
    \u7ECF\u5B9E\u76D8\u68C0\u9A8C\uFF0C\u672C\u5730\u5316\u5F00\u53D1\u90E8\u7F72\uFF0C\u4FDD\u969C\u7B56\u7565\u5B89\u5168\u3002\n\n|jaqsflowchart|\n\nFeatures\n========\n\n- \u901A\u8FC7\u7EDF\u4E00\u7684\
    DataApi\uFF0C\u83B7\u53D6\u3001\u5B58\u50A8\u548C\u7BA1\u7406\u6570\u636E\u3002\n- \u901A\u8FC7\u6570\u5B66\u516C\u5F0F\u5FEB\u901F\u5B9A\u4E49\u5E76\u5206\u6790\u4FE1\u53F7\uFF1B\u5B9E\u73B0Alpha\u9009\
    \u80A1\u3001CTA\u3001\u5957\u5229\u7B49\u5404\u7C7B\u91CF\u5316\u4EA4\u6613\u7B56\u7565\uFF0C\u5BF9\u7B56\u7565\u8FDB\u884C\u5386\u53F2\u56DE\u6D4B\u3002\n- \u901A\u8FC7\u7EDF\u4E00\u7684TradeApi\uFF0C\
    \u63A5\u5165\u5728\u7EBF\u4EFF\u771F\u7CFB\u7EDF\u8FDB\u884C\u4EFF\u771F\u4EA4\u6613\uFF0C\u8DDF\u8E2A\u7B56\u7565\u8868\u73B0\u3002\u5BF9\u63A5\u5B9E\u76D8\u901A\u9053\u5B9E\u73B0\u5B9E\u76D8\u4EA4\
    \u6613\uFF08\u5F53\u7136\u9700\u8981\u7528\u6237\u641E\u5B9A\u4EA4\u6613\u901A\u9053\uFF09\u3002\n- \u5B8C\u5168\u672C\u5730\u5316\uFF0C\u4EE3\u7801\u53EF\u4EE5\u90E8\u7F72\u5728\u4EFB\u610F\u4E2A\u4EBA\
    \u7535\u8111\u6216\u670D\u52A1\u5668\u4E0A\uFF0C\u672C\u5730\u5316\u8FD0\u884C\uFF0C\u7B56\u7565\u5B89\u5168\u6027\u6709\u4FDD\u8BC1\u3002\n- \u6A21\u5757\u5316\u8BBE\u8BA1\uFF0C\u901A\u8FC7\u6807\u51C6\
    \u7684\u8F93\u5165\u8F93\u51FA\u63A5\u53E3\uFF0C\u505A\u5230\u6570\u636E\u4E0E\u56DE\u6D4B\u5206\u79BB\uFF0C\u4EA4\u6613\u4E0E\u5206\u6790\u5206\u79BB\uFF0C \u6BCF\u4E00\u4E2A\u73AF\u8282\u90FD\u6E05\
    \u6670\u53EF\u63A7\uFF0C\u8FBE\u5230\u673A\u6784\u7EA7\u522B\u7684\u6807\u51C6\u5316\u3001\u6D41\u7A0B\u5316\u3002\n- \u9762\u5411\u5B9E\u76D8\u7F16\u7A0B\uFF0C\u6570\u636E\u6784\u5EFA\u65F6\u8FDB\u884C\
    \u4E25\u683C\u7684\u5BF9\u9F50\uFF0C\u56DE\u6D4B\u65F6\u63D0\u4F9B\u5F53\u524D\u5FEB\u7167\u800C\u4E0D\u662F\u6570\u636E\u67E5\u8BE2\u63A5\u53E3\uFF0C\u9632\u6B62\u672A\u6765\u51FD\u6570\u7684\u51FA\
    \u73B0\uFF1B\u901A\u8FC7\u5BF9\u7B56\u7565\u7C7B\u7684\u7CBE\u5DE7\u8BBE\u8BA1\uFF0C\u4F7F\u56DE\u6D4B\u4E0E\u5B9E\u76D8/\u4EFF\u771F\u4EA4\u6613\u53EF\u4F7F\u7528\u540C\u4E00\u5957\u7B56\u7565\u4EE3\
    \u7801\uFF0C\u59CB\u4E8E\u5F00\u5C55\u4E25\u8C28\u7684\u7814\u7A76\u3001\u56DE\u6D4B\u3002\n\nInstallation\n============\n\n\u53C2\u89C1 \\ `\u5B89\u88C5\u6307\u5357 <https://github.com/quantOS-org/JAQS/blob/master/doc/install.md>`__\\\
    \n\nQuickstart\n==========\n\n\u53C2\u89C1 \\ `\u7528\u6237\u624B\u518C <http://www.quantos.org/jaqs/doc.html>`__\\.\n\n\u66F4\u591A\u793A\u4F8B\u53EF\u5728\u9879\u76EE\u7684 ``example`` \u6587\u4EF6\
    \u5939\u4E0B\u627E\u5230\uFF0C\u5982 ``example/alpha/select_stocks_pe_profit.py`` .\n\n\u67E5\u770B\u5B8C\u6574\u6587\u6863\uFF0C\u8BF7\u8BBF\u95EE\uFF1A \\ `jaqs.readthedocs.io <http://jaqs.readthedocs.io>`__\\\
    \ \n\nContribute\n===========\n\n\u6B22\u8FCE\u53C2\u4E0E\u5F00\u53D1\uFF01\u53EF\u4EE5\u901A\u8FC7Pull Request\u7684\u65B9\u5F0F\u63D0\u4EA4\u4EE3\u7801\u3002\n\n\nQuestions\n==========\n\n- \u5982\
    \u679C\u60A8\u53D1\u73B0BUG\uFF0C\u8BF7\u5230\\ `\u8FD9\u91CC <https://github.com/quantOS-org/JAQS/issues/new>`__\\\u63D0\u4EA4\u3002\n- \u5982\u679C\u6709\u95EE\u9898\u3001\u5EFA\u8BAE\uFF0C\u4E5F\u53EF\
    \u4EE5\u5230 \\ `\u793E\u533A <https://www.quantos.org/community>`__\\ \u53C2\u4E0E\u8BA8\u8BBA\u3002\n\n\u63D0\u95EE\u524D\uFF0C\u8BF7\u67E5\u770B \\ `\u5982\u4F55\u6B63\u786E\u63D0\u95EE <https://github.com/quantOS-org/JAQS/blob/master/doc/how_to_ask_questions.md>`__\\\
    \ \u3002\n\n\nLicense\n=======\n\nApache 2.0\u8BB8\u53EF\u534F\u8BAE\u3002\u7248\u6743\u6240\u6709(c)2017 quantOS-org.\n\n\n\n.. |jaqsflowchart| image:: https://raw.githubusercontent.com/quantOS-org/jaqs/master/doc/img/jaqs.png\n\
    \n.. |pypi peoject version| image:: https://img.shields.io/pypi/v/jaqs.svg\n   :target: https://pypi.python.org/pypi/jaqs\n.. |pypi license| image:: https://img.shields.io/pypi/l/jaqs.svg\n   :target:\
    \ https://opensource.org/licenses/Apache-2.0\n.. |pypi pyversion| image:: https://img.shields.io/pypi/pyversions/jaqs.svg\n   :target: https://pypi.python.org/pypi/jaqs\n.. |travis ci| image:: https://travis-ci.org/quantOS-org/JAQS.svg?branch=master\n\
    \   :target: https://travis-ci.org/quantOS-org/JAQS\n.. |covergae| image:: https://coveralls.io/repos/github/quantOS-org/JAQS/badge.svg?branch=master\n \_ :target: https://coveralls.io/github/quantOS-org/JAQS?branch=master\n\
    \n\n"
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
