language: python

python:
    - "2.7"

branches:
  only:
  - master

before_install:
  - apt-get install libsnappy-dev

install:
  - pip install -r requirements_test.txt

script:
- py.test test/test_align.py test/test_dataservice.py test/test_data_basic.py test/test_calendar.py test/test_data_api.py --cov=jaqs

after_success:
  - coveralls
