language: python

python:
    - "2.7"

branches:
  only:
  - master

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libsnappy-dev

install:
  - pip install -r requirements_test.txt

before_script:
  - python setup.py install

script:
  - py.test test/test_util.py --cov=jaqs

after_success:
  - coveralls
